### ISSUE TITLE
detector output after NMS?

### ISSUE THREAD

**Issue by minouei-kl** [LourencoVazPato/seeing-without-looking#2]
Congratulation on your work. 
I want to ask did you use the detector's output after NMS or before it? 
since in the mmdetection the default post-processing is NMS.

**Comment by LourencoVazPato** [comment]
Thks,
I used the detector output after NMS (done by default by mmdetection) and then applied Contextual Rescoring.

You could also use it without NMS although it can give you different results

**Comment by minouei-kl** [comment]
Hi,
since you have much experience in this matter, do you think is it possible to have a small rescoring network that can be trained end to end with the detection network?
